services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      # Mounts the host Docker socket into the container for management
      - /var/run/docker.sock:/var/run/docker.sock
      # Uses a named volume for persistent storage of Portainer's configuration
      - portainer_data:/data
    ports:
      # Exposes the secure HTTPS UI port
      - "9443:9443"

  reverse-proxy:
    container_name: "reverse-proxy"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: "host"

    environment:
      TZ: "America/Denver"

      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${DRIVE_POOL_PREFIX}/jellyfin/config:/config
      - ${DRIVE_POOL_PREFIX}/cache:/cache
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/media
        target: /media
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/media2
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      # - JELLYFIN_PublishedServerUrl=http://example.com

    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  portainer_data:
    # Ensures a volume named 'portainer_data' is created and managed by Docker
    name: portainer_data
