---
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      # Mounts the host Docker socket into the container for management
      - /var/run/docker.sock:/var/run/docker.sock
      # Uses a named volume for persistent storage of Portainer's configuration
      - portainer_data:/data
    ports:
      # Exposes the secure HTTPS UI port
      - "9443:9443"

  reverse-proxy:
    container_name: "reverse-proxy"
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    network_mode: "host"

    environment:
      TZ: "America/Denver"

      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp

    # DRIVE_POOL_PREFIX defaults to /zdata/. Configure as necessary.
    volumes:
      - ${DRIVE_POOL_PREFIX}/.config/jellyfin:/config
      - ${DRIVE_POOL_PREFIX}/.cache/jellyfin:/cache
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/video
        target: /media
        read_only: true

        # Optional extra fonts used during transcoding with subtitle burn-in
        # - type: bind
        #   source: /path/to/fonts
        #   target: /usr/local/share/fonts/custom
        #   read_only: true

    restart: "unless-stopped"

    # Optional docker healthcheck if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: "audiobookshelf"
    ports:
      - 13378:80

    # DRIVE_POOL_PREFIX defaults to /zdata/. Configure as necessary.
    volumes:
      - ${DRIVE_POOL_PREFIX}/.config/audiobookshelf:/config
      - ${DRIVE_POOL_PREFIX}/.cache/audiobookshelf:/metadata
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/audio/audiobooks
        target: /audiobooks
        read_only: true
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/audio/podcasts
        target: /podcasts
        read_only: true

    environment:
      TZ: "America/Denver"

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    # NOTE Mounted volumes are not read_only bc syncthing runs peer-to-peer.
    # The classic server/client model does not apply.
    volumes:
      - ${DRIVE_POOL_PREFIX}/.config/syncthing:/config
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/documents
        target: /documents

      - type: bind
        source: ${DRIVE_POOL_PREFIX}/archive
        target: /archive

      # Optional obsidian sync directory.
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/obsidian
        target: /obsidian

      # Optional taskwarrior directory.
      # Set this up to sync to ~/.task on devices.
      - type: bind
        source: ${DRIVE_POOL_PREFIX}/taskwarrior
        target: /taskwarrior

    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

volumes:
  portainer_data:
    # Ensures a volume named 'portainer_data' is created and managed by Docker
    name: portainer_data
