name: Lint Docker Compose

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint docker-compose.yml
        run: yamllint docker-compose.yml

  docker_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ephemeral .env file
        run: |
          touch .env
          echo DRIVE_POOL_PREFIX=invalid >> .env

      - name: Validate docker compose config
        run: docker compose config
